# Welcome to Jekyll!
#

# Site settings
title: EventVertex
description: |
  Where Your Event Reaches New Heights!
owner: Abba Daniel # or company name
first_published: 2024 # if migrating another site, the year of your first publish
email: abba.fred.daniel@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/FrederickAbba
  github: https://github.com/Abba-F-Daniel1

# Build settings
markdown: kramdown
#sass:
#  style: compressed
